# Generated by Django 3.2 on 2021-05-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoModels',
            new_name='PhotoModel',
        ),
    ]
